# Generated by Django 4.2.23 on 2025-07-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='modelos/')),
            ],
        ),
    ]
