# Generated by Django 4.2.23 on 2025-07-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('modelo', 'Modelo'), ('fotografo', 'Fotógrafo'), ('produtor', 'Produtor'), ('maquiador', 'Maquiador'), ('estilista', 'Estilista'), ('cabeleleiro', 'Cabeleleiro')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='profissionais/')),
            ],
        ),
    ]
